### PR TITLE
Removed all instance where fragmentation in regex could cause a test …

### PR DESCRIPTION
**Pull request by dpwspoon**
…failure

### CODE REVIEW

**Comment by sanjay-saxena** [comment]
Failed on Travis in BBOSH.

**Comment by cmebarrow** [comment]
Should we just fix [read /:.*/ "\n" sometimes not working correctly #200](https://github.com/k3po/k3po/issues/200) instead?

**Comment by dpwspoon** [comment]
@cmebarrow Why not both ? :-)

In a few cases I've seen people write scripts like the following...

```
read /regex/
read "\n"
```

So there will still be an educational issue here, though it will be less pronounced if we do proposed fix in https://github.com/k3po/k3po/issues/200.  And then they will always have this fallback if thats what they actually prefer

**Comment by jitsni** [comment]
Regex matching is tricky if you don't know the end of input. Say the script
is
```
read /a*/
read a
```
If the data comes in different events, then you need to sufficiently wait
until all the data arrives. Then there are cases like below which are
ambiguous to match:

```
read /a*/
read a
```
Difficult to match
```
read /a*/
read /b*/
```

In some cases we may need to build a bigger regex to match stream of data.


On Tue, Apr 12, 2016 at 5:16 PM, David Witherspoon <notifications@github.com

**Comment by dpwspoon** [comment]
For now I think we should merge this and always try to use the single regex with terminator included in the regex.  This PR makes that change across the board.

**Pull request merged**
