### PR TITLE
Fix clean-up issue in ControlServerHandler

### PR DESCRIPTION
**Pull request by StCostea**
Fix for https://github.com/k3po/k3po/issues/400

### CODE REVIEW

**Comment by dpwspoon** [comment]
The build for this is failing

**Comment by dpwspoon** [comment]
Travis failed with 

```
Running org.kaazing.specification.ws.extensions.x_kaazing_idle_timeout.IdleTimeoutExtensionIT
java.lang.IllegalArgumentException: Unexpected event kind: NOTIFIED
	at org.kaazing.k3po.junit.rules.ScriptRunner.dispose(ScriptRunner.java:227)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.evaluate(SpecificationStatement.java:137)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[INFO] Control channel caught exception event: java.nio.channels.ClosedChannelException
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 24.667 sec <<< FAILURE! - in org.kaazing.specification.ws.extensions.x_kaazing_idle_timeout.IdleTimeoutExtensionIT
standardPingPongFramesSentByServerNoClientTimeout(org.kaazing.specification.ws.extensions.x_kaazing_idle_timeout.IdleTimeoutExtensionIT)  Time elapsed: 7.019 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 7 seconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.kaazing.k3po.junit.rules.ScriptRunner.notifyBarrier(ScriptRunner.java:203)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.notifyBarrier(SpecificationStatement.java:150)
	at org.kaazing.k3po.junit.rules.K3poRule.notifyBarrier(K3poRule.java:250)
	at org.kaazing.specification.ws.extensions.x_kaazing_idle_timeout.IdleTimeoutExtensionIT.standardPingPongFramesSentByServerNoClientTimeout(IdleTimeoutExtensionIT.java:120)


Results :

Tests in error: 
  IdleTimeoutExtensionIT.standardPingPongFramesSentByServerNoClientTimeout:120 » TestTimedOut
```

I suspect this may be related to changes in the control?

**Comment by StCostea** [comment]
The main cause is a timeout of the test that is sending the abort. The
exception is caused by bad handling of dispose command/ disposed event on
abort. The issue was there before my changes, maybe it was not visible in
the logs. It is on my list of to do's for k3po. We can add a different
issue for it.

On Feb 9, 2017 19:48, "David Witherspoon" <notifications@github.com> wrote:

Travis failed with

Running org.kaazing.specification.ws.extensions.x_kaazing_idle_timeout.IdleTimeoutExtensionIT
java.lang.IllegalArgumentException: Unexpected event kind: NOTIFIED
	at org.kaazing.k3po.junit.rules.ScriptRunner.dispose(ScriptRunner.java:227)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.evaluate(SpecificationStatement.java:137)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[INFO] Control channel caught exception event:
java.nio.channels.ClosedChannelException
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 24.667
sec <<< FAILURE! - in
org.kaazing.specification.ws.extensions.x_kaazing_idle_timeout.IdleTimeoutExtensionIT
standardPingPongFramesSentByServerNoClientTimeout(org.kaazing.specification.ws.extensions.x_kaazing_idle_timeout.IdleTimeoutExtensionIT)
 Time elapsed: 7.019 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 7 seconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.kaazing.k3po.junit.rules.ScriptRunner.notifyBarrier(ScriptRunner.java:203)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.notifyBarrier(SpecificationStatement.java:150)
	at org.kaazing.k3po.junit.rules.K3poRule.notifyBarrier(K3poRule.java:250)
	at org.kaazing.specification.ws.extensions.x_kaazing_idle_timeout.IdleTimeoutExtensionIT.standardPingPongFramesSentByServerNoClientTimeout(IdleTimeoutExtensionIT.java:120)


Results :

Tests in error:
  IdleTimeoutExtensionIT.standardPingPongFramesSentByServerNoClientTimeout:120
» TestTimedOut

I suspect this may be related to changes in the control?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/k3po/k3po/pull/401#issuecomment-278718116>, or mute the
thread

**Comment by dpwspoon** [comment]
Filed: https://github.com/k3po/k3po/issues/402

**Pull request merged**
